### ISSUE TITLE
[bug][v9]Door buttons fail to show with the module enabled.

### ISSUE THREAD

**Issue by Janner3D** [flamewave000/dragonflagon-arch#104] opened 2022-01-07 23:20 UTC
**Describe the issue**
Door buttons fail to show with the module enabled.

**To Reproduce**
1. Activate the Module
2. Create a door
3. Select a player token

**Expected behavior**
Door buttons should be visible.

**Comment by flamewave000** [comment] 2022-01-07 23:22
Duplicate of #87. DF Architect is currently being migrated to V9.

**Closed by flamewave000** 2022-01-07 23:22 UTC
Labels: bug
