### ISSUE TITLE
Walls Edited into Doors Cannot Be Opened or Closed

### ISSUE THREAD

**Issue by Regniwekim** [flamewave000/dragonflagon-arch#114] opened 2022-02-16 02:59 UTC
**Describe the issue**
When DF Architect is active, walls that were edited into doors from within their settings can't be open or closed. 

**To Reproduce**
1. Create a wall
2. Open the wall's settings by double clicking it
3. Set 'Is Door' to either Door or Secret
4. All Door Icons will disappear, leaving you unable to open or close them.

**Expected behavior**
Door icons should remain and be usable.

**Screenshots (Optional)**
![df_off](https://user-images.githubusercontent.com/6635697/154187590-38e8bad4-91fb-4f90-b09f-774693da37f8.png)
![df_on](https://user-images.githubusercontent.com/6635697/154187597-6acc1431-0a37-4426-b73b-4b1993fb0096.png)

**Comment by flamewave000** [comment] 2022-02-16 05:01
Duplicate of #107

Please update your version of Architect.

**Closed by flamewave000** 2022-02-16 05:01 UTC
Labels: bug
