### ISSUE TITLE
I can't capture images in foundry

### ISSUE THREAD

**Issue by dkaerit** [flamewave000/dragonflagon-arch#168] opened 2023-01-10 23:46 UTC
**Describe the issue**
It won't let me take a screenshot of my scene in which I only have the map and mosaics on.
I have checked that I do not have any modules installed that conflict

foundry version: 10.285
dnd 5e version: 2.0.3

![ezgif-1-2741eac686](https://user-images.githubusercontent.com/24440929/211685282-683b9590-1dd2-4cd2-b869-3486782b1294.gif)

**Comment by flamewave000** [comment] 2023-01-11 06:44
Duplicate of #142 and #143 

This is an issue due to the foundry changes in v10. The feature has been temporarily disabled until I can rebuild it to work on v10.

**Closed by flamewave000** 2023-01-11 06:44 UTC
Labels: bug
