### ISSUE TITLE
Doors glitching out

### ISSUE THREAD

**Issue by Nedrapter** [flamewave000/dragonflagon-arch#107] opened 2022-01-12 06:21 UTC
**Describe the issue**
After transitioning to v9 door are not interactable and do not show icons anymore while the module is active. They remain at the state they were (open or closed) and cannot be changed by players or the GM. No error is shown on the console.
**To Reproduce**
1. Activate the module
2. Check the doors.

**Expected behavior**
Door icons to be visible and doors to be interactable.

**Screenshots (Optional)**
The two screenshots are from the Wall layer and the Token layer controls. The doors seem to be there but they behave as described above.
![image](https://user-images.githubusercontent.com/74311190/149074476-b6fad4d1-ea53-4fe8-9a95-a4e03b488b85.png)
![image](https://user-images.githubusercontent.com/74311190/149074520-a0c53186-5348-4d2c-bde4-b493bf0cfd9e.png)

I have deactivated all other modules, re-installed the module, tried it on different scenes and worlds. Console does not show errors. Both players and me (the GM) cannot interact with doors. Once the module is deactivated, they behave normally.

**Comment by flamewave000** [comment] 2022-01-12 06:30
Duplicate of #87

**Comment by flamewave000** [comment] 2022-01-12 06:32
DF Architect 3.1.x does not support Foundry V9. Please wait for DF Architect v3.2.x.
You can follow the progress here: [FoundryVTT V9 Migration](https://github.com/flamewave000/dragonflagon-arch/milestone/2)

**Closed by flamewave000** 2022-01-12 06:32 UTC
Labels: bug
